{
 "title": "Device Performance",
 "time": { "from": "2022-11-01T00:00:00.000Z", "to": "2023-05-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "device_identifier",
    "label": "Device Identifier",
    "query": "SELECT DISTINCT device_identifier FROM kpi_1d ORDER BY device_identifier;\n"
   },
   {
    "name": "start_date",
    "label": "Start Date",
    "query": "SELECT DISTINCT to_char(time, 'YYYY-MM') as month_year\nFROM kpi_1d\nORDER BY month_year;\n"
   },
   {
    "name": "end_date",
    "label": "End Date",
    "query": "SELECT DISTINCT to_char(time, 'YYYY-MM') as month_year\nFROM kpi_1d\nORDER BY month_year;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "The percentage of Device ID ${device_identifier} with KPI Alerts versus without Alerts ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "WITH AlertCounts AS (\n    SELECT \n        device_identifier,\n        SUM(CASE WHEN kpi_alert_count > 0 THEN 1 ELSE 0 END) AS alerting_devices,\n        SUM(CASE WHEN kpi_alert_count = 0 THEN 1 ELSE 0 END) AS non_alerting_devices\n    FROM kpi_1d\n    WHERE device_identifier IN (${device_identifier}) AND time >= to_date('${start_date}', 'YYYY-MM') AND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\n    GROUP BY device_identifier\n)\n\nSELECT \n    'With Alerts' AS category, \n    SUM(alerting_devices) AS count\nFROM AlertCounts\nUNION ALL\nSELECT \n    'Without Alerts' AS category, \n    SUM(non_alerting_devices) AS count\nFROM AlertCounts;\n"
    }
   ]
  },
  {
   "title": "The distribution of different alert conditions for Device ID ${device_identifier}",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kpi_alert_condition_type_last, COUNT(*) as count\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_alert_condition_type_last;\n"
    }
   ]
  },
  {
   "title": "Distribution of Alerts by KPI for Device ID ${device_identifier}",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    kpi_type_code,\n    COUNT(*) AS alert_count\nFROM kpi_1d\nWHERE kpi_alert_count > 0 AND device_identifier IN (${device_identifier}) AND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY alert_count DESC;\n"
    }
   ]
  },
  {
   "title": "Yearly Alert Summary for Device ID ${device_identifier}",
   "type": "barchart",
   "description": "The yearly trend of alerts",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('year', time) as year, SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nGROUP BY year\nORDER BY year;"
    }
   ]
  },
  {
   "title": "The number of times each KPIs went **Above or Below** the alert threshold for Device ID ${device_identifier}",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, COUNT(*) as occurrences\nFROM kpi_1d\nWHERE \n    (kpi_value_last < kpi_alert_condition_lower_limit_last OR kpi_value_last > kpi_alert_condition_upper_limit_last)\nAND kpi_alert_count > 0 \nAND device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY occurrences DESC;\n"
    }
   ]
  },
  {
   "title": "The number of times each KPIs went **Above** the alert threshold for Device ID ${device_identifier}",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, COUNT(*) as occurrences\nFROM kpi_1d\nWHERE kpi_value_last > kpi_alert_condition_upper_limit_last \nAND device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY occurrences DESC;\n"
    }
   ]
  },
  {
   "title": "The number of times each KPIs went **Below** the alert threshold for Device ID ${device_identifier}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, COUNT(*) as occurrences\nFROM kpi_1d\nWHERE kpi_value_last < kpi_alert_condition_lower_limit_last\nAND device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY occurrences DESC;\n"
    }
   ]
  },
  {
   "title": "Top Number of KPIs with Most Alerts for Device ID ${device_identifier} ",
   "type": "barchart",
   "description": " To identify which KPIs frequently trigger alerts",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, COUNT(*) as occurrences\nFROM kpi_1d\nWHERE \n    (kpi_value_last < kpi_alert_condition_lower_limit_last OR kpi_value_last > kpi_alert_condition_upper_limit_last)\nAND kpi_alert_count > 0 \nAND device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY occurrences DESC;\n"
    }
   ]
  },
  {
   "title": "The number of KPI samples that met the alert condition for each KPI type for Device ID ${device_identifier}",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code;\n"
    }
   ]
  },
  {
   "title": "Average KPI value over time for Device ID ${device_identifier}",
   "type": "timeseries",
   "description": "Display the average KPI value over time for a specific device.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time,  kpi_value_avg\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';"
    }
   ]
  },
  {
   "title": "Average alert count over time for Device ID ${device_identifier}",
   "type": "timeseries",
   "description": "Display the alert count value over time for a specific device.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "rawSql": "SELECT \n    time,\n    AVG(kpi_alert_count) AS avg_alerts\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "The density or intensity of average alerts count over time for Device ID ${device_identifier}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('month', time) AS month, \n    AVG(kpi_alert_count) AS avg_alerts\n  FROM kpi_1d\nWHERE device_identifier = ${device_identifier}\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY \n    date_trunc('month', time)\nORDER BY \n    month;\n"
    }
   ]
  },
  {
   "title": "KPI Alert Count for Device ID ${device_identifier}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';"
    }
   ]
  },
  {
   "title": "KPIs Close to Alert Thresholds for Device ID ${device_identifier}",
   "type": "bargauge",
   "description": "KPIs close to their alert thresholds but haven't triggered an alert yet.\n",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, kpi_type_code, kpi_value_last, kpi_alert_condition_lower_limit_last, kpi_alert_condition_upper_limit_last\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nAND kpi_alert_count = 0\nAND (kpi_value_last < kpi_alert_condition_lower_limit_last + 10 OR kpi_value_last > kpi_alert_condition_upper_limit_last - 10);\n\n"
    }
   ]
  },
  {
   "title": "All time Monthly Average of KPIs for Device ID ${device_identifier}",
   "type": "barchart",
   "gridPos": { "h": 74, "w": 24, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('month', time) as month, kpi_type_code, AVG(kpi_value_avg) as monthly_avg\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nGROUP BY month, kpi_type_code\nORDER BY month, kpi_type_code;"
    }
   ]
  },
  {
   "title": "All data for Device ID ${device_identifier}",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 208 },
   "targets": [
    {
     "rawSql": "SELECT * FROM kpi_1d \nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';\n"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 217 } },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 223 } }
 ]
}