{
 "title": "Testing",
 "time": { "from": "2022-11-17T00:00:00.000Z", "to": "2023-01-25T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "device_identifier",
    "label": "Device Identifier",
    "query": "SELECT DISTINCT device_identifier FROM kpi_1d ORDER BY device_identifier;\n"
   },
   {
    "name": "start_date",
    "label": "Start Date",
    "query": "SELECT DISTINCT to_char(time, 'YYYY-MM') as month_year\nFROM kpi_1d\nORDER BY month_year;\n"
   },
   {
    "name": "end_date",
    "label": "End Date",
    "query": "SELECT DISTINCT to_char(time, 'YYYY-MM') as month_year\nFROM kpi_1d\nORDER BY month_year;\n"
   },
   {
    "name": "org_identifier",
    "label": "Organizational Identifier",
    "query": "SELECT DISTINCT org_identifier FROM kpi_1d ORDER BY org_identifier;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "The number of KPI samples that met the alert condition for each KPI type for Device ID${device_identifier}",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code;\n"
    }
   ]
  },
  {
   "title": "Average KPI value over time for Device ID ${device_identifier}",
   "type": "timeseries",
   "description": "Display the average KPI value over time for a specific device.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time, kpi_type_code, kpi_value_avg\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';"
    }
   ]
  },
  {
   "title": "kpi_type",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM kpi_type ORDER BY code"
    }
   ]
  },
  {
   "title": "The density or intensity of KPI values over time.",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT time, kpi_type_code, kpi_value_avg\nFROM kpi_1d\nWHERE device_identifier = ${device_identifier}\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\n"
    }
   ]
  },
  {
   "title": "KPI Alert Count for Device ID${device_identifier}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';"
    }
   ]
  },
  {
   "title": "The distribution of different alert conditions.",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kpi_alert_condition_type_last, COUNT(*) as count\nFROM kpi_1d\nWHERE device_identifier IN (${device_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_alert_condition_type_last;\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT time, kpi_type_code, kpi_value_avg, kpi_alert_count, kpi_alert_condition_text_last\nFROM kpi_1d\nWHERE time BETWEEN '2023-01-01' AND '2023-01-31';\n\n"
    }
   ]
  },
  {
   "title": "kpi_1d",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT * FROM kpi_1d WHERE time = (select max(time) from kpi_1d) AND device_identifier = (SELECT max(device_identifier) FROM kpi_1d) ORDER BY kpi_type_code "
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 } }
 ]
}