{
 "title": "Organization Performance",
 "time": { "from": "2022-11-01T00:00:00.000Z", "to": "2023-05-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "org_identifier",
    "label": "Organization Identifier",
    "query": "SELECT DISTINCT org_identifier FROM kpi_1d ORDER BY org_identifier;\n"
   },
   {
    "name": "start_date",
    "label": "Start Date",
    "query": "SELECT DISTINCT to_char(time, 'YYYY-MM') as month_year\nFROM kpi_1d\nORDER BY month_year;\n"
   },
   {
    "name": "end_date",
    "label": "End Date",
    "query": "SELECT DISTINCT to_char(time, 'YYYY-MM') as month_year\nFROM kpi_1d\nORDER BY month_year;\n"
   }
  ]
 },
 "panels": [
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "The percentage of all Devices with Alerts versus without Alerts for Organization ID ${org_identifier}",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "WITH AlertCounts AS (\n    SELECT \n        device_identifier,\n        SUM(CASE WHEN kpi_alert_count > 0 THEN 1 ELSE 0 END) AS alerting_devices,\n        SUM(CASE WHEN kpi_alert_count = 0 THEN 1 ELSE 0 END) AS non_alerting_devices\n    FROM kpi_1d\n    WHERE time >= to_date('${start_date}', 'YYYY-MM') AND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month' \n    AND org_identifier IN (${org_identifier})\n    GROUP BY device_identifier\n)\n\nSELECT \n    'Devices with Alerts' AS category, \n    SUM(alerting_devices) AS count\nFROM AlertCounts\nUNION ALL\nSELECT \n    'Devices without Alerts' AS category, \n    SUM(non_alerting_devices) AS count\nFROM AlertCounts;\n"
    }
   ]
  },
  {
   "title": "Distribution of Alerts by KPI for All Devices for Organization ID ${org_identifier}",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    kpi_type_code,\n    COUNT(*) AS alert_count\nFROM kpi_1d\nWHERE kpi_alert_count > 0 AND (time >= to_date('${start_date}', 'YYYY-MM') AND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month' )\nAND org_identifier IN (${org_identifier})\nGROUP BY kpi_type_code\nORDER BY alert_count DESC;\n"
    }
   ]
  },
  {
   "title": "Yearly Alert Summary for Organization ID ${org_identifier}",
   "type": "barchart",
   "description": "The yearly trend of alerts",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('year', time) as year, SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nGROUP BY year\nORDER BY year;"
    }
   ]
  },
  {
   "title": "The number of times each KPIs went **Above or Below** the alert threshold for Organization ID ${org_identifier}",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, COUNT(*) as occurrences\nFROM kpi_1d\nWHERE (kpi_value_last < kpi_alert_condition_lower_limit_last OR kpi_value_last > kpi_alert_condition_upper_limit_last)\nAND org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY occurrences DESC;\n"
    }
   ]
  },
  {
   "title": "The number of times each KPIs went **Above** the alert threshold for Organization ID ${org_identifier}",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, COUNT(*) as occurrences\nFROM kpi_1d\nWHERE kpi_value_last > kpi_alert_condition_upper_limit_last \nAND org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY occurrences DESC;\n"
    }
   ]
  },
  {
   "title": "The number of times each KPIs went **Below** the alert threshold for Organization ID ${org_identifier}",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, COUNT(*) as occurrences\nFROM kpi_1d\nWHERE (kpi_value_last < kpi_alert_condition_lower_limit_last)\nAND org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code\nORDER BY occurrences DESC;\n"
    }
   ]
  },
  {
   "title": "Top Number of KPIs with Most Alerts for Organization ID ${org_identifier} ",
   "type": "barchart",
   "description": " To identify which KPIs frequently trigger alerts",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nAND (time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month')\nGROUP BY kpi_type_code\nORDER BY total_alerts DESC\nLIMIT 10; -- Top 10 KPIs"
    }
   ]
  },
  {
   "title": "The number of KPI samples that met the alert condition for each KPI type for Organization ID ${org_identifier}",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT kpi_type_code, SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_type_code;\n"
    }
   ]
  },
  {
   "title": "Average KPI value over time for Organization ID ${org_identifier}",
   "type": "timeseries",
   "description": "Display the average KPI value over time for a specific device.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time,  kpi_value_avg\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';"
    }
   ]
  },
  {
   "title": "Average alert count over time for Organization ID ${org_identifier}",
   "type": "timeseries",
   "description": "Display the alert count value over time for a specific device.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT \n    time,\n    AVG(kpi_alert_count) AS avg_alerts\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "The density or intensity of average alerts count over time for Organization ID ${org_identifier}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('month', time) AS month, \n    AVG(kpi_alert_count) AS avg_alerts\n  FROM kpi_1d\nWHERE org_identifier = ${org_identifier}\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY \n    date_trunc('month', time)\nORDER BY \n    month;\n"
    }
   ]
  },
  {
   "title": "KPI Alert Count for Organization ID ${org_identifier}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(kpi_alert_count) as total_alerts\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';"
    }
   ]
  },
  {
   "title": "The distribution of different alert conditions for Organization ID ${org_identifier}",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kpi_alert_condition_type_last, COUNT(*) as count\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nGROUP BY kpi_alert_condition_type_last;\n"
    }
   ]
  },
  {
   "title": "KPIs Close to Alert Thresholds for Organization ID ${org_identifier}",
   "type": "bargauge",
   "description": "KPIs close to their alert thresholds but haven't triggered an alert yet.\n",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, kpi_type_code, kpi_value_last, kpi_alert_condition_lower_limit_last, kpi_alert_condition_upper_limit_last\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month'\nAND kpi_alert_count = 0\nAND (kpi_value_last < kpi_alert_condition_lower_limit_last + 10 OR kpi_value_last > kpi_alert_condition_upper_limit_last - 10);\n\n"
    }
   ]
  },
  {
   "title": "All time Monthly Average of KPIs for Organization ID ${org_identifier}",
   "type": "barchart",
   "gridPos": { "h": 74, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('month', time) as month, kpi_type_code, AVG(kpi_value_avg) as monthly_avg\nFROM kpi_1d\nWHERE org_identifier IN (${org_identifier})\nGROUP BY month, kpi_type_code\nORDER BY month, kpi_type_code;"
    }
   ]
  },
  {
   "title": "All data for Organization ID ${org_identifier}",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 209 },
   "targets": [
    {
     "rawSql": "SELECT * FROM kpi_1d \nWHERE org_identifier IN (${org_identifier})\nAND time >= to_date('${start_date}', 'YYYY-MM')\nAND time < to_date('${end_date}', 'YYYY-MM') + INTERVAL '1 month';\n"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 218 } }
 ]
}